application: searchtweets
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /matrix(.*)
  script: admin.py
  login: admin
  
- url: .*
  script: controller.py
