application: searchtweets
version: 1-1
runtime: python
api_version: 1

handlers:

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /static
  static_dir: static

- url: /matrix(.*)
  script: admin.py
  login: admin
  
- url: .*
  script: controller.py
